services:
  backend:
    build:
      context: ./backend
    # image: nandes009/my-image-converter-backend:latest
    ports:
      - 9090:9090
    volumes:
      - ./backend/converted_images:/go/src/app/converted_images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: nandes009/my-image-converter-frontend
    ports:
      - 8081:80